todo-aspnetmvc-ui/Models/ErrorViewModel.cs
namespace todo_aspnetmvc_ui.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

todo-aspnetmvc-ui/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using todo_aspnetmvc_ui.Models;

namespace todo_aspnetmvc_ui.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [Route("/Privacy")]
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

todo-aspnetmvc-ui/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using todo_domain_entities;
using todo_domain_entities.Services;

namespace todo_aspnetmvc_ui.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;
        private readonly IListService _listService;

        public ItemController(IItemService itemService, IListService listService)
        {
            _itemService = itemService;
            _listService = listService;
        }

        // GET: Item
        [HttpGet("/Item")]
        public async Task<IActionResult> Index(int? listId)
        {
            if(listId.HasValue)
                return View(await _itemService.GetItemsByListId(listId.Value));
            
            var items = await _itemService.GetItems();
            
            return View(items);
        }
        

        // GET: Item/Details/5
        [HttpGet("/Item/Details/{id:int}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            
            var todoItem = await _itemService.GetItemById(id.Value);
            return View(todoItem);
        }

        // GET: Item/Create
        [HttpGet("/Item/Create")]
        public async Task<IActionResult> Create()
        {
            var lists = await _listService.GetLists();
            ViewData["ToDoListId"] = new SelectList(lists, "Id", "Title");
            return View();
        }

        // POST: Item/Create
        [HttpPost("/Item/Create")]
        public async Task<IActionResult> Create(TodoItem todoItem)
        {
            await _itemService.AddItem(todoItem);
            return RedirectToAction(nameof(Index));
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var todoItem = await _itemService.GetItemById(id.Value);
            var lists = await _listService.GetLists();
            ViewData["ToDoListId"] = new SelectList(lists, "Id", "Title", todoItem.ToDoListId);
            return View(todoItem);
        }

        // POST: Item/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, TodoItem todoItem)
        {
            if (id != todoItem.Id)
            {
                return NotFound();
            }

            try
            {
                await _itemService.UpdateItem(todoItem);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_itemService.TodoItemExists(todoItem.Id))
                {
                    return NotFound();
                }

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var todoItem = await _itemService.GetItemById(id.Value);

            return View(todoItem);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _itemService.DeleteItem(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

todo-aspnetmvc-ui/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using todo_domain_entities;
using todo_domain_entities.Services;

namespace todo_aspnetmvc_ui.Controllers
{
    public class TodoController : Controller
    {
        private readonly IListService _listService;
        private readonly IItemService _itemService;

        public TodoController(IListService listService, IItemService itemService)
        {
            _listService = listService;
            _itemService = itemService;
        }

        // GET:
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var lists = await _listService.GetLists();
            foreach (var list in lists)
            {
                list.Items = await _itemService.GetItemsByListId(list.Id);
            }
            
            return View(lists);
        }

        // GET: Todo/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            
            var todoList = await _listService.GetListById(id.Value);

            return View(todoList);
        }

        // GET: Todo/Create
        [HttpGet]
        public IActionResult Create() => View();

        // POST: Todo/Create
        [HttpPost]
        public async Task<IActionResult> Create(TodoList todoList)
        {
            if (!ModelState.IsValid) 
                return View(todoList);

            await _listService.AddList(todoList);
            return RedirectToAction(nameof(Index));
        }

        // GET: Todo/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var todoList = await _listService.GetListById(id.Value);

            return View(todoList);
        }

        // POST: Todo/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, TodoList todoList)
        {
            if (id != todoList.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(todoList);
            
            try
            {
                await _listService.UpdateList(todoList);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_listService.TodoListExists(todoList.Id))
                {
                    return NotFound();
                }
                
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Todo/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var todoList = await _listService.GetListById(id.Value);

            return View(todoList);
        }

        // POST: Todo/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _listService.DeleteList(id);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Copy(int id)
        {
            await _listService.CopyList(id);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Hide(int id)
        {
            var todoList = await _listService.GetListById(id);
            todoList.IsHidden = true;
            await _listService.UpdateList(todoList);

            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public async Task<IActionResult> Show()
        {
            var lists = await _listService.GetLists();
            var hiddenLists = lists.Where(x => x.IsHidden = false);
            await _listService.UpdateRangeOfLists(hiddenLists);
            
            return RedirectToAction(nameof(Index));
        }
    }
}

todo-aspnetmvc-ui/Views/Item/Create.cshtml
@model todo_domain_entities.TodoItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create new Task</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="@State.NotStarted">Not Started</option>
                    <option value="@State.InProgress">In Progress</option>
                    <option value="@State.Completed">Completed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDoListId" class="control-label"></label>
                <select asp-for="ToDoListId" class ="form-control" asp-items="ViewBag.ToDoListId"></select>
            </div>
            <div class="form-group">
                <div class="btn-group" role="group">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
                <div class="btn-group" role="group">
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-aspnetmvc-ui/Views/Item/Delete.cshtml
@model todo_domain_entities.TodoItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete the task</h1>

<h3>Are you sure you want to delete this task?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Title
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Description
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Status
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Creation Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            Due Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            Todo List
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TodoList!.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

todo-aspnetmvc-ui/Views/Item/Details.cshtml
@model todo_domain_entities.TodoItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details of the task</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Title
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Description
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Status
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Creation Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            Due Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            Todo List
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TodoList.Title)
        </dd>
    </dl>
</div>
<div class="btn-group" role="group">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
</div>
<div class="btn-group" role="group">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

todo-aspnetmvc-ui/Views/Item/Edit.cshtml
@model todo_domain_entities.TodoItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit the task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="@State.NotStarted">Not Started</option>
                    <option value="@State.InProgress">In Progress</option>
                    <option value="@State.Completed">Completed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDoListId" class="control-label"></label>
                <select asp-for="ToDoListId" class="form-control" asp-items="ViewBag.ToDoListId"></select>
                <span asp-validation-for="ToDoListId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="btn-group" role="group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
                <div class="btn-group" role="group">
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-aspnetmvc-ui/Views/Item/Index.cshtml
@model IEnumerable<todo_domain_entities.TodoItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Tasks to do</h1>

<div class="btn-group" role="group">
    <a asp-action="Create" class="btn btn-success btn-sm">Create new task</a>
</div>
<div class="btn-group" role="group">
    <div class="form-check">
        <input class="form-check-input" type="checkbox" id="hideCompleted" onchange="hideCompletedItems(this.checked)">
        <label class="form-check-label" for="hideCompleted">
            Hide Completed Items
        </label>
    </div>
</div>
<table class="table table-hover" aria-describedby="list of items">
    <thead>
    <tr>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            Status
        </th>
        <th>
            Creation Date
        </th>
        <th>
            Due Date
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr class="@(item.IsCompleted ? "completed" : "")">
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

todo-aspnetmvc-ui/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - todo_aspnetmvc_ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Todo" asp-action="Index">To Do App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Show all lists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Show all items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - ToDoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="js/itemScripts.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

todo-aspnetmvc-ui/Views/Todo/Create.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create new List</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="btn-group" role="group">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
                <div class="btn-group" role="group">
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

todo-aspnetmvc-ui/Views/Todo/Delete.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete the list</h1>

<h3>Are you sure you want to delete the list?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Title
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Description
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

todo-aspnetmvc-ui/Views/Todo/Details.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Details";
}

<h1>Details of the list</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Title
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            Description
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Items
        </dt>
        <dd class = "col-sm-10">
            @Model.Items.Count
        </dd>
    </dl>
</div>
<div class="btn-group" role="group">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
</div>
<div class="btn-group" role="group">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

todo-aspnetmvc-ui/Views/Todo/Edit.cshtml
@model todo_domain_entities.TodoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit the list</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group"></div>
            <div class="form-group">
                <div class="btn-group" role="group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
                <div class="btn-group" role="group">
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

todo-aspnetmvc-ui/Views/Todo/Index.cshtml
@model IEnumerable<todo_domain_entities.TodoList>

@{
    ViewData["Title"] = "Index";
}

<h1>To do lists</h1>
<div class="btn-group" role="group">
    <a asp-action="Create" class="btn btn-success btn-sm">Create New List</a>
</div>
<div class="btn-group" role="group">
    <a asp-action="Show" class="btn btn-success btn-sm">Show hidden lists</a>
</div>
<table class="table table-hover" aria-describedby="head table">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Items
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
    @if (!item.IsHidden)
    {
        <tr>
            <td>
                <a asp-controller="Item" asp-action="Index" asp-route-listId="@item.Id">
                    @Html.DisplayFor(modelItem => item.Title)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @item.Items.Count
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a>
                <a asp-action="Copy" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Copy</a>
                <a asp-action="Hide" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Hide</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
        @foreach (var todoItem in item.Items.Where(ti => ti.DueDate.HasValue && ti.DueDate.Value.Date == DateTime.Today))
        {
            <tr class="table table-sm">
                <td class="table-warning"></td>
                <td class="table-warning">Tasks due today:</td>
                <td class="table-warning">@Html.DisplayFor(modelItem => todoItem.Title)</td>
            </tr>
        }
    }
}
    </tbody>
</table>